# Generated by Django 5.0.6 on 2024-05-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('opening_hours', models.CharField(default='', max_length=200)),
                ('image', models.FileField(blank=True, upload_to='attraction_images/')),
                ('address', models.CharField(default='', max_length=150)),
                ('price', models.CharField(default='', max_length=150)),
                ('link', models.CharField(default='', max_length=200)),
                ('category', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
